-- ============================================================
-- AceBank Lite v2.0 — Migration Script from v1.0
-- ============================================================
-- Use this script to upgrade an existing v1.0 database to v2.0
-- without losing existing data.

USE himdata;

-- 1. Modify USERS table
ALTER TABLE USERS 
ADD COLUMN ROLE ENUM('CUSTOMER', 'ADMIN') DEFAULT 'CUSTOMER',
ADD COLUMN PHONE VARCHAR(15),
ADD COLUMN DATE_OF_BIRTH DATE,
ADD COLUMN ADDRESS TEXT,
ADD COLUMN PAN_NO VARCHAR(10),
ADD COLUMN STATUS ENUM('ACTIVE', 'LOCKED', 'SUSPENDED') DEFAULT 'ACTIVE',
ADD COLUMN FAILED_LOGIN_ATTEMPTS INT DEFAULT 0,
ADD COLUMN LOCKED_UNTIL TIMESTAMP NULL,
ADD COLUMN TWO_FA_ENABLED BOOLEAN DEFAULT FALSE,
ADD COLUMN TWO_FA_SECRET VARCHAR(64),
ADD COLUMN PROFILE_PHOTO VARCHAR(512),
ADD COLUMN UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE INDEX idx_users_email ON USERS(EMAIL);
CREATE INDEX idx_users_status ON USERS(STATUS);
CREATE INDEX idx_users_role ON USERS(ROLE);

-- 2. Modify ACCOUNTS table
ALTER TABLE ACCOUNTS
ADD COLUMN VERSION INT DEFAULT 0,
ADD COLUMN CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_accounts_user ON ACCOUNTS(USER_ID);
CREATE INDEX idx_accounts_status ON ACCOUNTS(STATUS);

-- 3. Modify LOAN_APPLICATIONS table
ALTER TABLE LOAN_APPLICATIONS
ADD COLUMN REVIEWED_BY INT,
ADD COLUMN REVIEW_NOTES TEXT,
ADD COLUMN REVIEWED_AT TIMESTAMP NULL,
ADD FOREIGN KEY (REVIEWED_BY) REFERENCES USERS(USER_ID);

CREATE INDEX idx_loan_account ON LOAN_APPLICATIONS(ACCOUNT_NO);
CREATE INDEX idx_loan_status ON LOAN_APPLICATIONS(STATUS);

-- 4. Modify TRANSACTIONS table
ALTER TABLE TRANSACTIONS
ADD COLUMN REFERENCE_NO VARCHAR(36);

CREATE INDEX idx_tx_sender ON TRANSACTIONS(SENDER_ACCOUNT);
CREATE INDEX idx_tx_receiver ON TRANSACTIONS(RECEIVER_ACCOUNT);
CREATE INDEX idx_tx_type ON TRANSACTIONS(TX_TYPE);
CREATE INDEX idx_tx_created ON TRANSACTIONS(CREATED_AT);
CREATE INDEX idx_tx_reference ON TRANSACTIONS(REFERENCE_NO);

-- 5. Create NOTIFICATIONS table
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT NOT NULL,
    MESSAGE         TEXT NOT NULL,
    TYPE            VARCHAR(30) NOT NULL DEFAULT 'INFO',
    IS_READ         BOOLEAN DEFAULT FALSE,
    ICON            VARCHAR(100),
    ACTION_LINK     VARCHAR(255),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    INDEX idx_notif_account (ACCOUNT_NO),
    INDEX idx_notif_read (IS_READ),
    INDEX idx_notif_created (CREATED_AT)
);

-- 6. Create OTP_STORE table
CREATE TABLE IF NOT EXISTS OTP_STORE (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL           VARCHAR(255) NOT NULL,
    OTP_HASH        VARCHAR(255) NOT NULL,
    ACCOUNT_NO      INT,
    PURPOSE         ENUM('PASSWORD_RESET', 'LOGIN_2FA', 'TRANSACTION') DEFAULT 'PASSWORD_RESET',
    EXPIRES_AT      TIMESTAMP NOT NULL,
    VERIFIED        BOOLEAN DEFAULT FALSE,
    ATTEMPTS        INT DEFAULT 0,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_otp_email (EMAIL),
    INDEX idx_otp_expires (EXPIRES_AT)
);

-- 7. Create BENEFICIARIES table
CREATE TABLE IF NOT EXISTS BENEFICIARIES (
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    OWNER_ACCOUNT       INT NOT NULL,
    BENEFICIARY_ACCOUNT INT NOT NULL,
    BENEFICIARY_NAME    VARCHAR(255) NOT NULL,
    BANK_NAME           VARCHAR(255) DEFAULT 'AceBank',
    IFSC_CODE           VARCHAR(11) DEFAULT 'ACEB0000001',
    NICKNAME            VARCHAR(100),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OWNER_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    UNIQUE KEY uk_beneficiary (OWNER_ACCOUNT, BENEFICIARY_ACCOUNT),
    INDEX idx_benef_owner (OWNER_ACCOUNT)
);

-- 8. Create SCHEDULED_TRANSFERS table
CREATE TABLE IF NOT EXISTS SCHEDULED_TRANSFERS (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    FROM_ACCOUNT    INT NOT NULL,
    TO_ACCOUNT      INT NOT NULL,
    AMOUNT          DECIMAL(15, 2) NOT NULL,
    SCHEDULE_TYPE   ENUM('ONE_TIME', 'DAILY', 'WEEKLY', 'MONTHLY') NOT NULL,
    NEXT_EXECUTION  TIMESTAMP NOT NULL,
    LAST_EXECUTED   TIMESTAMP NULL,
    STATUS          ENUM('ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED') DEFAULT 'ACTIVE',
    REMARK          VARCHAR(255),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FROM_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    FOREIGN KEY (TO_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO),
    INDEX idx_sched_from (FROM_ACCOUNT),
    INDEX idx_sched_next (NEXT_EXECUTION),
    INDEX idx_sched_status (STATUS)
);

-- 9. Create CARD_REQUESTS table
CREATE TABLE IF NOT EXISTS CARD_REQUESTS (
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO          INT NOT NULL,
    CARD_TYPE           ENUM('DEBIT', 'CREDIT', 'ATM') NOT NULL,
    REQUEST_TYPE        ENUM('NEW', 'REPLACEMENT', 'BLOCK', 'UNBLOCK') NOT NULL,
    STATUS              ENUM('PENDING', 'APPROVED', 'REJECTED', 'ISSUED', 'BLOCKED') DEFAULT 'PENDING',
    CARD_NUMBER_MASKED  VARCHAR(19),
    IS_BLOCKED          BOOLEAN DEFAULT FALSE,
    REASON              TEXT,
    REVIEWED_BY         INT,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    FOREIGN KEY (REVIEWED_BY) REFERENCES USERS(USER_ID),
    INDEX idx_card_account (ACCOUNT_NO),
    INDEX idx_card_status (STATUS)
);

-- 10. Create FIXED_DEPOSITS table
CREATE TABLE IF NOT EXISTS FIXED_DEPOSITS (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT NOT NULL,
    AMOUNT          DECIMAL(15, 2) NOT NULL,
    INTEREST_RATE   DECIMAL(5, 2) NOT NULL,
    TENURE_MONTHS   INT NOT NULL,
    MATURITY_DATE   DATE NOT NULL,
    MATURITY_AMOUNT DECIMAL(15, 2) NOT NULL,
    STATUS          ENUM('ACTIVE', 'MATURED', 'CLOSED', 'PREMATURE_CLOSED') DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    INDEX idx_fd_account (ACCOUNT_NO),
    INDEX idx_fd_status (STATUS),
    INDEX idx_fd_maturity (MATURITY_DATE)
);

-- 11. Create RECURRING_DEPOSITS table
CREATE TABLE IF NOT EXISTS RECURRING_DEPOSITS (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT NOT NULL,
    MONTHLY_AMOUNT  DECIMAL(15, 2) NOT NULL,
    INTEREST_RATE   DECIMAL(5, 2) NOT NULL,
    TENURE_MONTHS   INT NOT NULL,
    TOTAL_DEPOSITED DECIMAL(15, 2) DEFAULT 0.00,
    MATURITY_AMOUNT DECIMAL(15, 2) NOT NULL,
    STATUS          ENUM('ACTIVE', 'MATURED', 'CLOSED') DEFAULT 'ACTIVE',
    NEXT_DEBIT_DATE DATE NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    INDEX idx_rd_account (ACCOUNT_NO),
    INDEX idx_rd_status (STATUS)
);

-- 12. Create BILL_PAYMENTS table
CREATE TABLE IF NOT EXISTS BILL_PAYMENTS (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT NOT NULL,
    BILLER_NAME     VARCHAR(255) NOT NULL,
    BILLER_CATEGORY ENUM('ELECTRICITY', 'WATER', 'GAS', 'INTERNET', 'MOBILE', 'DTH', 'INSURANCE', 'OTHER') NOT NULL,
    AMOUNT          DECIMAL(15, 2) NOT NULL,
    REFERENCE_NO    VARCHAR(36),
    CONSUMER_NO     VARCHAR(50),
    STATUS          ENUM('COMPLETED', 'PENDING', 'FAILED') DEFAULT 'COMPLETED',
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    INDEX idx_bill_account (ACCOUNT_NO),
    INDEX idx_bill_category (BILLER_CATEGORY)
);

-- 13. Create COMPLAINTS table
CREATE TABLE IF NOT EXISTS COMPLAINTS (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT NOT NULL,
    TICKET_NO       VARCHAR(20) UNIQUE NOT NULL,
    SUBJECT         VARCHAR(255) NOT NULL,
    DESCRIPTION     TEXT NOT NULL,
    CATEGORY        ENUM('TRANSACTION', 'ACCOUNT', 'CARD', 'LOAN', 'TECHNICAL', 'OTHER') NOT NULL,
    STATUS          ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') DEFAULT 'OPEN',
    PRIORITY        ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') DEFAULT 'MEDIUM',
    RESOLUTION      TEXT,
    ASSIGNED_TO     INT,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    FOREIGN KEY (ASSIGNED_TO) REFERENCES USERS(USER_ID),
    INDEX idx_complaint_account (ACCOUNT_NO),
    INDEX idx_complaint_status (STATUS),
    INDEX idx_complaint_ticket (TICKET_NO)
);

-- 14. Create AUDIT_LOG table
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT,
    USER_ID         INT,
    ACTION          VARCHAR(100) NOT NULL,
    DETAILS         TEXT,
    IP_ADDRESS      VARCHAR(45),
    USER_AGENT      VARCHAR(512),
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_audit_account (ACCOUNT_NO),
    INDEX idx_audit_user (USER_ID),
    INDEX idx_audit_action (ACTION),
    INDEX idx_audit_created (CREATED_AT)
);

-- 15. Create KYC_DOCUMENTS table
CREATE TABLE IF NOT EXISTS KYC_DOCUMENTS (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT NOT NULL,
    DOCUMENT_TYPE   ENUM('AADHAAR', 'PAN', 'PASSPORT', 'VOTER_ID', 'DRIVING_LICENSE', 'ADDRESS_PROOF', 'PHOTO') NOT NULL,
    FILE_NAME       VARCHAR(255) NOT NULL,
    FILE_PATH       VARCHAR(512) NOT NULL,
    FILE_SIZE       BIGINT,
    MIME_TYPE       VARCHAR(100),
    STATUS          ENUM('PENDING', 'VERIFIED', 'REJECTED') DEFAULT 'PENDING',
    VERIFIED_BY     INT,
    REJECTION_REASON TEXT,
    VERIFIED_AT     TIMESTAMP NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE,
    FOREIGN KEY (VERIFIED_BY) REFERENCES USERS(USER_ID),
    INDEX idx_kyc_account (ACCOUNT_NO),
    INDEX idx_kyc_status (STATUS)
);

-- 16. Create LOGIN_ATTEMPTS table
CREATE TABLE IF NOT EXISTS LOGIN_ATTEMPTS (
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO      INT,
    IP_ADDRESS      VARCHAR(45) NOT NULL,
    SUCCESS         BOOLEAN NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_login_account (ACCOUNT_NO),
    INDEX idx_login_ip (IP_ADDRESS),
    INDEX idx_login_created (CREATED_AT)
);

-- Seed default admin user if not exists
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AADHAAR_NO, EMAIL, PASSWORD_HASH, ROLE, PHONE, STATUS)
SELECT 'Admin', 'AceBank', '000000000000', 'admin@acebank.com', 
       '$2a$12$LJ3m4ys3PQFXqJZ8gY8OPOkVbKjHiXsNXpJjLYMh0qy8.XkKVvKCe', 
       'ADMIN', '+919999999999', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'admin@acebank.com');

INSERT INTO ACCOUNTS (ACCOUNT_NO, USER_ID, ACCOUNT_TYPE, BALANCE, STATUS)
SELECT 10000001, (SELECT USER_ID FROM USERS WHERE EMAIL = 'admin@acebank.com'), 'SAVINGS', 1000000.00, 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM ACCOUNTS WHERE ACCOUNT_NO = 10000001);
